### Test API
GET http://localhost:5000/


### Register User 1 and 2
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Khushal2",
  "email": "khushal2@test.com",
  "password": "123456",
  "skills": "React, Node.js",
  "college": "Anurag University",
  "bio": "MERN student developer"
}


### Login User 1
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "khushal@test.com",
  "password": "123456"
}


### login user 2
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "khushal2@test.com",
  "password": "123456"
}

### Create Project
POST http://localhost:5000/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZkMzU4MTMyYTE2M2M1NjE3OGE0MCIsIm5hbWUiOiJLaHVzaGFsIiwiZW1haWwiOiJraHVzaGFsQHRlc3QuY29tIiwiaWF0IjoxNzgxNTE5Mjc4LCJleHAiOjE3ODIxMjQwNzh9.O3uKL_C2ajHMZA1nmdzRwaV8QY0LZY6zsX_HLc_ZwAg

{
  "title": "Build College Website",
  "description": "Need a React website for college event",
  "budget": 3000,
  "deadline": "2026-06-25"
}


### Get All Projects
GET http://localhost:5000/api/projects


### place bid

POST http://localhost:5000/api/projects/6a2fd405132a163c56178a41/bids
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZkNTU4MTMyYTE2M2M1NjE3OGE0MyIsIm5hbWUiOiJLaHVzaGFsMiIsImVtYWlsIjoia2h1c2hhbDJAdGVzdC5jb20iLCJpYXQiOjE3ODE1MTk5NjQsImV4cCI6MTc4MjEyNDc2NH0.ogx9hsoXlVALY-4jIdyDMZ7kTvazgMhedM3vp_mtq-Q

{
  "amount": 2500,
  "message": "I can complete this project within 3 days."
}

### get project details

GET http://localhost:5000/api/projects/6a2fd405132a163c56178a41


### accept the bid

PUT http://localhost:5000/api/bids/6a2fd670132a163c56178a44/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZkMzU4MTMyYTE2M2M1NjE3OGE0MCIsIm5hbWUiOiJLaHVzaGFsIiwiZW1haWwiOiJraHVzaGFsQHRlc3QuY29tIiwiaWF0IjoxNzgxNTIwMTg2LCJleHAiOjE3ODIxMjQ5ODZ9.8lCMOK_AgQTI5JptlXdrQglPGdQ1P_DWFbHaO7ta9fw

{}


###get dasboard datw
GET http://localhost:5000/api/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZkMzU4MTMyYTE2M2M1NjE3OGE0MCIsIm5hbWUiOiJLaHVzaGFsIiwiZW1haWwiOiJraHVzaGFsQHRlc3QuY29tIiwiaWF0IjoxNzgxNTIwMTg2LCJleHAiOjE3ODIxMjQ5ODZ9.8lCMOK_AgQTI5JptlXdrQglPGdQ1P_DWFbHaO7ta9fw